from enum import Enum


class Curio(Enum):
    DRAGONPIT_SWORD = "DRAGONPIT_SWORD"
    TAI_E_SWORD = "TAI_E_SWORD"
    EVIL_REPELLER = "DRAGONPIT_SWORD"
    COSMIC_NET = "COSMIC_NET"
    HEAVENLY_FLAME_SEAL = "HEAVENLY_FLAME_SEAL"
    COSMIC_DEMON_SPIRE = "COSMIC_DEMON_SPIRE"
    EARTH_VAST_RULER = "EARTH_VAST_RULER"
    ARCTIC_DRAGON_HALBERD = "ARCTIC_DRAGON_HALBERD"
    FIRE_LOTUS = "FIRE_LOTUS"
    SOUL_DESTROYER = "SOUL_DESTROYER"
    OCEAN_PACIFIER = "OCEAN_PACIFIER"
