from enum import Enum


class CultivationType(Enum):
    CORPORIA = "CORPORIA"
    MAGICKA = "MAGICKA"
    SWORDIA = "SWORDIA"
    GHOSTIA = "GHOSTIA"


class CultivationLevel(Enum):
    NOVICE = "NOVICE"
    CONNECTION = "CONNECTION"
    FOUNDATION = "FOUNDATION"
    VIRTUOSO = "VIRTUOSO"
    NASCENT_SOUL = "NASCENT_SOUL"
    INCARNATION = "INCARNATION"
    VOIDBREAK = "VOIDBREAK"
    WHOLENESS = "WHOLENESS"
    PERFECTION = "PERFECTION"
    NIRVANA = "NIRVANA"


class Relic(Enum):
    # Physical
    BELL = "BELL"
    CHAIN = "CHAIN"
    DRUM = "DRUM"
    PAGODA = "PAGODA"
    SEAL = "SEAL"
    # Magical
    AMULET = "AMULET"
    BANNER = "BANNER"
    CAULDRON = "CAULDRON"
    GOURD = "GOURD"
    PEARL = "PEARL"
    MIRROR = "MIRROR"
    TRIGRAM = "TRIGRAM"
    # Swordia
    GREATSWORD = "GREATSWORD"
    LONGSWORD = "LONGSWORD"
    # Ghostia
    ARMGUARD = "ARMGUARD"
    FLAG = "FLAG"
    MASK = "MASK"
    ROPE = "ROPE"
    SOUL_BANNER = "SOUL_BANNER"
    # SWORDIA DIVINITY
    CYANCREST = "CYANCREST"
    # MAGICKA DIVINITY
    ROBE = "ROBE"
    UMBRELLA = "UMBRELLA"
    FLASK = "FLASK"
    ARMOR = "ARMOR"
    BLADE = "BLADE"
    BELLS = "BELLS"


class Weapon(Enum):
    FAN = "FAN"
    DOUBLE_PATH_FAN = "DOUBLE_PATH_FAN"
    SWORD = "SWORD"
    DOUBLE_PATH_SWORD = "DOUBLE_PATH_SWORD"


class Armour(Enum):
    ARMOR = "ARMOR"
    DOUBLE_PATH_ARMOR = "DOUBLE_PATH_ARMOR"
    ROBE = "ROBE"
    DOUBLE_PATH_ROBE = "DOUBLE_PATH_ROBE"


class Accessory(Enum):
    PENDANT = "PENDANT"
    DOUBLE_PATH_PENDANT = "DOUBLE_PATH_PENDANT"
    BRACELET = "BRACELET"
    DOUBLE_PATH_BRACELET = "DOUBLE_PATH_BRACELET"


class Curio(Enum):
    DRAGONPIT_SWORD = "DRAGONPIT_SWORD"
    TAI_E_SWORD = "TAI_E_SWORD"
    EVIL_REPELLER = "DRAGONPIT_SWORD"
    COSMIC_NET = "COSMIC_NET"
    HEAVENLY_FLAME_SEAL = "HEAVENLY_FLAME_SEAL"
    COSMIC_DEMON_SPIRE = "COSMIC_DEMON_SPIRE"
    EARTH_VAST_RULER = "EARTH_VAST_RULER"
    ARCTIC_DRAGON_HALBERD = "ARCTIC_DRAGON_HALBERD"
    FIRE_LOTUS = "FIRE_LOTUS"
    SOUL_DESTROYER = "SOUL_DESTROYER"
    OCEAN_PACIFIER = "OCEAN_PACIFIER"
