"""add literatia to taoists

Revision ID: aa00912c84c1
Revises: 5dd5d07be078
Create Date: 2025-08-23 20:33:30.307196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa00912c84c1'
down_revision: Union[str, Sequence[str], None] = '5dd5d07be078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taoists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('literatia_stage_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('literatia_minor_stage', sa.Enum('EARLY', 'MIDDLE', 'LATE', name='cultivationminorstage'), nullable=True))
        batch_op.create_foreign_key("fk_taoists_literatia_stage_id", 'CultivationStage', ['literatia_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taoists', schema=None) as batch_op:
        batch_op.drop_constraint("fk_taoists_literatia_stage_id", type_='foreignkey')
        batch_op.drop_column('literatia_minor_stage')
        batch_op.drop_column('literatia_stage_id')

    # ### end Alembic commands ###
