from .base import Base
from sqlalchemy import Column, Integer, Float, String, ForeignKey, Enum
from sqlalchemy.orm import relationship

from models.cultivation import CultivationMinorStage, Divinity


class Taoist(Base):
    __tablename__ = "taoists"
    id = Column(Integer, primary_key=True)

    # Basic info
    name = Column(String, nullable=False)
    total_br = Column(Float, nullable=False)

    # Relic + curios
    weapon_id = Column(Integer, ForeignKey("Relic.id"))
    armour_id = Column(Integer, ForeignKey("Relic.id"))
    accessory_id = Column(Integer, ForeignKey("Relic.id"))
    curio_1_id = Column(Integer, ForeignKey("Curio.id"))
    curio_2_id = Column(Integer, ForeignKey("Curio.id"))
    curio_3_id = Column(Integer, ForeignKey("Curio.id"))
    relic_1_id = Column(Integer, ForeignKey("Relic.id"))
    relic_2_id = Column(Integer, ForeignKey("Relic.id"))
    relic_3_id = Column(Integer, ForeignKey("Relic.id"))
    relic_4_id = Column(Integer, ForeignKey("Relic.id"))
    relic_5_id = Column(Integer, ForeignKey("Relic.id"))
    relic_6_id = Column(Integer, ForeignKey("Relic.id"))
    # Pet + Ability
    pet_front_id = Column(Integer, ForeignKey("Pet.id"))
    pet_front_rarity = Column(Integer, ForeignKey("RarityLevel.id"))
    pet_left_id = Column(Integer, ForeignKey("Pet.id"))
    pet_left_rarity = Column(Integer, ForeignKey("RarityLevel.id"))
    pet_right_id = Column(Integer, ForeignKey("Pet.id"))
    pet_right_rarity = Column(Integer, ForeignKey("RarityLevel.id"))
    ability_0_id = Column(Integer, ForeignKey("Ability.id"))
    ability_1_id = Column(Integer, ForeignKey("Ability.id"))
    ability_2_id = Column(Integer, ForeignKey("Ability.id"))
    ability_3_id = Column(Integer, ForeignKey("Ability.id"))
    ability_4_id = Column(Integer, ForeignKey("Ability.id"))
    ability_5_id = Column(Integer, ForeignKey("Ability.id"))

    # Cultivation
    swordia_stage_id = Column(Integer, ForeignKey("CultivationStage.id"), nullable=False)
    swordia_minor_stage = Column(Enum(CultivationMinorStage))
    corporia_stage_id = Column(Integer, ForeignKey("CultivationStage.id"), nullable=False)
    corporia_minor_stage = Column(Enum(CultivationMinorStage))
    magicka_stage_id = Column(Integer, ForeignKey("CultivationStage.id"), nullable=False)
    magicka_minor_stage = Column(Enum(CultivationMinorStage))
    ghostia_stage_id = Column(Integer, ForeignKey("CultivationStage.id"), nullable=False)
    ghostia_minor_stage = Column(Enum(CultivationMinorStage))
    # Divine cultivation
    alignment = Column(Enum(Divinity))
    daemonfae_stage = Column(Integer)
    daemonfae_minor_stage = Column(Enum(CultivationMinorStage))

    # BR breakdown
    character = Column(Float)
    technique = Column(Float)
    relic = Column(Float)
    ability = Column(Float)
    curio = Column(Float)
    pet = Column(Float)
    zodiac = Column(Float)
    law = Column(Float)
    immortal = Column(Float)
    daemonfae = Column(Float)
    divinity = Column(Float)
    field = Column(Float)
    samsara = Column(Float)
    miniworld = Column(Float)

    # Stats
    hp = Column(Float)
    mp = Column(Float)
    p_attack = Column(Float)
    p_def = Column(Float)
    m_attack = Column(Float)
    m_def = Column(Float)
    ability_dmg_taoist = Column(Float)
    ability_dmg_reduction = Column(Float)
    relic_dmg_taoist = Column(Float)
    relic_dmg_reduction = Column(Float)
    dmg_demonic_taoist = Column(Float)
    demonic_taoist_dmg_reduction = Column(Float)
    dmg_divine_taoist = Column(Float)
    divine_taoist_dmg_reduction = Column(Float)
    p_pen = Column(Float)
    p_block = Column(Float)
    m_pen = Column(Float)
    m_block = Column(Float)
    crit_multiplier = Column(Float)
    crit_block = Column(Float)
    crit_dmg = Column(Float)
    crit = Column(Float)
    crit_res = Column(Float)
    resilience = Column(Float)
    paralysis_chance_boost = Column(Float)
    paralysis_chance_resist = Column(Float)
    paralysis_duration_boost = Column(Float)
    paralysis_duration_resist = Column(Float)
    paralysis_duration_boost_2 = Column(Float)
    paralysis_duration_reduction = Column(Float)
    paralysis_chance_reduction = Column(Float)
    curio_dmg_taoist = Column(Float)
    curio_dmg_reduction = Column(Float)
    p_hit = Column(Float)
    p_eva = Column(Float)
    m_hit = Column(Float)
    m_eva = Column(Float)
    dmg_bonus_monsters = Column(Float)
    monster_dmg_reduction = Column(Float)
    curio_dmg_monster = Column(Float)
    curio_dmg_pet = Column(Float)
    taoist_dmg_projection = Column(Float)
    law_suppression_boost = Column(Float)
    law_suppression_resist = Column(Float)
    mortal_ability_dmg_reduction = Column(Float)
    res_mortal_effects = Column(Float)
    spiritual_ability_dmg_reduction = Column(Float)
    res_spiritual_effects = Column(Float)
    spiritual_paralysis_resist = Column(Float)
    spiritual_blind_resist = Column(Float)
    spiritual_silence_resist = Column(Float)
    spiritual_curse_resist = Column(Float)
    sense = Column(Float)
    mspd = Column(Float)
    physique = Column(Float)
    agility = Column(Float)
    manipulation = Column(Float)
    occult_figure = Column(Float)
    hp_regen = Column(Float)
    mp_regen = Column(Float)
    projection_resist_taoist_dmg = Column(Float)

    # Relationships (optional for ORM)
    curio_1 = relationship("Curio", foreign_keys=[curio_1_id])
    curio_2 = relationship("Curio", foreign_keys=[curio_2_id])
    curio_3 = relationship("Curio", foreign_keys=[curio_3_id])
    weapon = relationship("Relic", foreign_keys=[weapon_id])
    armour = relationship("Relic", foreign_keys=[armour_id])
    accessory = relationship("Relic", foreign_keys=[accessory_id])
    relic_1 = relationship("Relic", foreign_keys=[relic_1_id])
    relic_2 = relationship("Relic", foreign_keys=[relic_2_id])
    relic_3 = relationship("Relic", foreign_keys=[relic_3_id])
    relic_4 = relationship("Relic", foreign_keys=[relic_4_id])
    relic_5 = relationship("Relic", foreign_keys=[relic_5_id])
    relic_6 = relationship("Relic", foreign_keys=[relic_6_id])
    pet_front = relationship("Pet", foreign_keys=[pet_front_id])
    pet_left = relationship("Pet", foreign_keys=[pet_left_id])
    pet_right = relationship("Pet", foreign_keys=[pet_right_id])
    ability_0 = relationship("Ability", foreign_keys=[ability_0_id])
    ability_1 = relationship("Ability", foreign_keys=[ability_1_id])
    ability_2 = relationship("Ability", foreign_keys=[ability_2_id])
    ability_3 = relationship("Ability", foreign_keys=[ability_3_id])
    ability_4 = relationship("Ability", foreign_keys=[ability_4_id])
    ability_5 = relationship("Ability", foreign_keys=[ability_5_id])
    corporia_stage = relationship("CultivationStage", foreign_keys=[corporia_stage_id])
    magicka_stage = relationship("CultivationStage", foreign_keys=[magicka_stage_id ])
    swordia_stage = relationship("CultivationStage", foreign_keys=[swordia_stage_id])
    ghostia_stage = relationship("CultivationStage", foreign_keys=[ghostia_stage_id])
